/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "poll.h"

bool_t
xdr_Vote (XDR *xdrs, Vote *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->voterid))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Candidates (XDR *xdrs, Candidates *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Candidates), (xdrproc_t) xdr_Candidates))
		 return FALSE;
	return TRUE;
}
