/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "poll.h"
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

/* Structure to hold voter information */
struct VoterList {
	int voterid;
	int votestatus;
	struct VoterList *next;
};

/* Structure to hold candidate information */
struct CandidateList {
	char name[50];
	int voteCount;
	struct CandidateList *next;
};

struct VoterList *voterlist;
struct CandidateList *candidatelist;

char **
zeroize_1_svc(void *argp, struct svc_req *rqstp)
{
    
	static char * result;
    
	struct VoterList *currentvoter = voterlist;
	struct VoterList *nextvoter;
	while(currentvoter != NULL)
	{
		nextvoter = currentvoter -> next;
		free(currentvoter);
		currentvoter = nextvoter;
	}
	voterlist = NULL;
	
	struct CandidateList *currentcandidate = candidatelist;
	struct CandidateList *nextcandidate;
	while(currentcandidate != NULL)
	{
		nextcandidate = currentcandidate -> next;
		free(currentcandidate);
		currentcandidate = nextcandidate;
	}
	candidatelist = NULL;
	result = "TRUE\n";
	printf("zeroize() called\n");
	return(&result);
}

/* Function to check if voter id already exists in the system.
 Parameters:	voterid
 Returns:	index, if found
 -1, otherwise
 */
int checkvoterstatus(int voterid)
{
	struct VoterList *current;// = (struct VoterList *)malloc(sizeof(struct VoterList));
	current = voterlist;
	int pos = 0;
	while(current != NULL)
	{
		if(current -> voterid == voterid)
		{
			return pos;
		}
		else
		{
			current = current -> next;
			pos = pos + 1;
		}
	}
	return -1;
}

char **
addvoter_1_svc(int *argp, struct svc_req *rqstp)
{
    
	static char * result;
    
	struct VoterList *current;// = (struct VoterList *)malloc(sizeof(struct VoterList));
	int pos = checkvoterstatus(*argp);
	if(pos != -1)
		result = "EXISTS\n";
	else
	{
		if(voterlist == NULL)
		{
			current = (struct VoterList *)malloc(sizeof(struct VoterList));
			current -> voterid = *argp;
			current -> votestatus = 0;
			current -> next = NULL;
			voterlist = current;
			result = "OK\n";
		}
		else
		{
			current = voterlist;
			while(current -> next != NULL)
				current = current -> next;
			current -> next = (struct VoterList *)malloc(sizeof(struct VoterList));
			current = current -> next;
			current -> voterid = *argp;
			current -> votestatus = 0;
			current -> next = NULL;
			result = "OK\n";
		}
	}
	printf("voter added\n");
	return(&result);
}

/* Function to check if candidate already exists.
 Parameters: char *name - name of the candidate
 Returns:	index, if exists
 -1 otherwise
 */
int checkcandidatestatus(char *name)
{
	int pos = 0;
	struct CandidateList *current;// = (struct CandidateList *)malloc(sizeof(struct CandidateList));
	current = candidatelist;
	while(current != NULL)
	{
		if(strcmp(current->name, name)==0)
		{
			return pos;
		}
		else
		{
			current = current -> next;
			pos = pos + 1;
		}
	}
	return -1;
}


/* Prints all registered candidates
 Parameters:	None
 Returns:	None
 */
void listallcandidates()
{
	struct CandidateList *current;// = (struct CandidateList *)malloc(sizeof(struct CandidateList));
	current = candidatelist;
	while(current != NULL)
	{
		printf("Voter name: %s Vote Count: %d\n", current->name, current->voteCount);
		current = current -> next;
	}
}


char **
votefor_1_svc(Vote *argp, struct svc_req *rqstp)
{
    
	static char * result;
    
	struct VoterList *currentvoter;// = (struct VoterList *)malloc(sizeof(struct VoterList));
	struct CandidateList *currentcandidate;// = (struct CandidateList *)malloc(sizeof(struct CandidateList));
	int pos, counter;
	pos = checkvoterstatus(argp->voterid);
	if(pos == -1)
		result = "NOTAVOTER\n";
	else
	{
		currentvoter = voterlist;
		for(counter = 0 ; counter < pos ; counter++)
			currentvoter = currentvoter -> next;
		if(currentvoter -> votestatus != 0)
		{
			result = "ALREADYVOTED\n";
		}
		else
		{
			currentvoter -> votestatus = 1;
			pos = checkcandidatestatus(argp->name);
			if(pos == -1)
			{
				if(candidatelist == NULL)
				{
					currentcandidate = (struct CandidateList *)malloc(sizeof(struct CandidateList));
					strcpy(currentcandidate -> name,argp->name);
					currentcandidate -> voteCount = 1;
					currentcandidate -> next = NULL;
					candidatelist = currentcandidate;
					result = "NEW\n";
				}
				else
				{
					currentcandidate = candidatelist;
					while(currentcandidate -> next != NULL)
						currentcandidate = currentcandidate -> next;
					currentcandidate -> next = (struct CandidateList *)malloc(sizeof(struct CandidateList));
					currentcandidate = currentcandidate -> next;
					strcpy(currentcandidate -> name,argp->name);
					currentcandidate -> voteCount = 1;
					currentcandidate -> next = NULL;
					result = "NEW\n";
				}
				
			}
			else
			{
				currentcandidate = candidatelist;
				for(counter = 0 ; counter < pos ; counter++)
					currentcandidate = currentcandidate -> next;
				currentcandidate->voteCount += 1;
				result = "CANDIDATEEXISTS\n";
			}
		}
	}
	printf("voter registered\n");
	return(&result);
}


Candidates *
listcandidates_1_svc(void *argp, struct svc_req *rqstp)
{
    
	static Candidates  *result;
    
	static Candidates *head;
	static Candidates *temp;
	struct CandidateList *current;
	current = candidatelist;
    
	while(current!=NULL)
	{
		if(head == NULL)
		{
			temp = (Candidates *)malloc(sizeof(Candidates));
			temp -> name = current -> name;
			temp -> next = NULL;
			head = temp;
		}
		else
		{
			temp = head;
			while(temp->next!=NULL)
				temp = temp -> next;
			temp->next = (Candidates *)malloc(sizeof(Candidates));
			temp = temp -> next;
			temp -> name = current -> name;
			temp -> next = NULL;
		}
		current = current -> next;
	}
	result = head;
	head = NULL;
	printf("listcandidates() called\n");
	return(&(*result));
}

int *
votecount_1_svc(char **argp, struct svc_req *rqstp)
{
    
	static int  result;
    
	printf("%s\n", *argp);
	struct CandidateList *current;// = (struct CandidateList *)malloc(sizeof(struct CandidateList));
	current = candidatelist;
	while(current != NULL)
	{
		if(strcmp(current->name, *argp)==0)
		{
			result = current->voteCount;
			printf("vote count retuned\n");
			return(&result);
		}
		else
		{
			current = current -> next;
		}
	}
	result = -1;
	printf("vote count returned\n");
	return(&result);
}
